spring:
  application:
    name: huddl-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/HUDDL
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

# JWT Configuration
jwt:
  secret: aHVkZGwtc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tYW5kLXZhbGlkYXRpb24tMjAyNA==
  expiration: 86400000 # 24 hours in milliseconds