spring:
  application:
    name: huddl-user-service
  datasource:
    url: jdbc:h2:mem:demohuddl
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

# JWT Configuration
jwt:
  secret: aHVkZGwtc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tYW5kLXZhbGlkYXRpb24tMjAyNA==
  expiration: 86400000 # 24 hours in milliseconds